### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by hujianxin** [lunaryorn/.emacs.d#34]
Hi, @lunaryorn . Your configuration is great, especially the scala part. I find some useful function in the file `flycheck-auto-scalastyle.el` and `flycheck-ensime.el`. I think it will be cool if you extract it to a singleton package.

**Comment by lunaryorn** [comment]
@hujianxin Thanks :blush: Makes me happy that you like it.

As for these libraries, though, you shouldn't use either.  `flycheck-auto-scalastyle.el` is redundant, because recent release of Flycheck do not use the JAR anymore and instead expect a `scalastyle` executable in `exec-path`.  

`flycheck-ensime` in turn is merely a proof of concept with some issues, which I didn't touch since quite some time.  I don't even know if it still works with recent Ensime versions.
